global using System;
global using Microsoft.Maui;
global using Microsoft.Maui.Platform;
global using Microsoft.Maui.Handlers;
global using Microsoft.Maui.Graphics;
global using System.Collections.Generic;
global using System.Threading.Tasks;
global using System.Linq;
global using Microsoft.Maui.Primitives;
global using Font = Microsoft.Maui.Font;